# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.1

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/michelebigi/Documents/Develop/ASTDYN/IOccultCalc

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/michelebigi/Documents/Develop/ASTDYN/IOccultCalc

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/opt/homebrew/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/opt/homebrew/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	cd /Users/michelebigi/Documents/Develop/ASTDYN/IOccultCalc && $(CMAKE_COMMAND) -E cmake_progress_start /Users/michelebigi/Documents/Develop/ASTDYN/IOccultCalc/CMakeFiles /Users/michelebigi/Documents/Develop/ASTDYN/IOccultCalc/external/IOC_StarMap//CMakeFiles/progress.marks
	cd /Users/michelebigi/Documents/Develop/ASTDYN/IOccultCalc && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 external/IOC_StarMap/all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/michelebigi/Documents/Develop/ASTDYN/IOccultCalc/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	cd /Users/michelebigi/Documents/Develop/ASTDYN/IOccultCalc && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 external/IOC_StarMap/clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	cd /Users/michelebigi/Documents/Develop/ASTDYN/IOccultCalc && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 external/IOC_StarMap/preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	cd /Users/michelebigi/Documents/Develop/ASTDYN/IOccultCalc && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 external/IOC_StarMap/preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	cd /Users/michelebigi/Documents/Develop/ASTDYN/IOccultCalc && $(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

# Convenience name for target.
external/IOC_StarMap/CMakeFiles/starmap.dir/rule:
	cd /Users/michelebigi/Documents/Develop/ASTDYN/IOccultCalc && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 external/IOC_StarMap/CMakeFiles/starmap.dir/rule
.PHONY : external/IOC_StarMap/CMakeFiles/starmap.dir/rule

# Convenience name for target.
starmap: external/IOC_StarMap/CMakeFiles/starmap.dir/rule
.PHONY : starmap

# fast build rule for target.
starmap/fast:
	cd /Users/michelebigi/Documents/Develop/ASTDYN/IOccultCalc && $(MAKE) $(MAKESILENT) -f external/IOC_StarMap/CMakeFiles/starmap.dir/build.make external/IOC_StarMap/CMakeFiles/starmap.dir/build
.PHONY : starmap/fast

src/StarMap.o: src/StarMap.cpp.o
.PHONY : src/StarMap.o

# target to build an object file
src/StarMap.cpp.o:
	cd /Users/michelebigi/Documents/Develop/ASTDYN/IOccultCalc && $(MAKE) $(MAKESILENT) -f external/IOC_StarMap/CMakeFiles/starmap.dir/build.make external/IOC_StarMap/CMakeFiles/starmap.dir/src/StarMap.cpp.o
.PHONY : src/StarMap.cpp.o

src/StarMap.i: src/StarMap.cpp.i
.PHONY : src/StarMap.i

# target to preprocess a source file
src/StarMap.cpp.i:
	cd /Users/michelebigi/Documents/Develop/ASTDYN/IOccultCalc && $(MAKE) $(MAKESILENT) -f external/IOC_StarMap/CMakeFiles/starmap.dir/build.make external/IOC_StarMap/CMakeFiles/starmap.dir/src/StarMap.cpp.i
.PHONY : src/StarMap.cpp.i

src/StarMap.s: src/StarMap.cpp.s
.PHONY : src/StarMap.s

# target to generate assembly for a file
src/StarMap.cpp.s:
	cd /Users/michelebigi/Documents/Develop/ASTDYN/IOccultCalc && $(MAKE) $(MAKESILENT) -f external/IOC_StarMap/CMakeFiles/starmap.dir/build.make external/IOC_StarMap/CMakeFiles/starmap.dir/src/StarMap.cpp.s
.PHONY : src/StarMap.cpp.s

src/catalog/CatalogManager.o: src/catalog/CatalogManager.cpp.o
.PHONY : src/catalog/CatalogManager.o

# target to build an object file
src/catalog/CatalogManager.cpp.o:
	cd /Users/michelebigi/Documents/Develop/ASTDYN/IOccultCalc && $(MAKE) $(MAKESILENT) -f external/IOC_StarMap/CMakeFiles/starmap.dir/build.make external/IOC_StarMap/CMakeFiles/starmap.dir/src/catalog/CatalogManager.cpp.o
.PHONY : src/catalog/CatalogManager.cpp.o

src/catalog/CatalogManager.i: src/catalog/CatalogManager.cpp.i
.PHONY : src/catalog/CatalogManager.i

# target to preprocess a source file
src/catalog/CatalogManager.cpp.i:
	cd /Users/michelebigi/Documents/Develop/ASTDYN/IOccultCalc && $(MAKE) $(MAKESILENT) -f external/IOC_StarMap/CMakeFiles/starmap.dir/build.make external/IOC_StarMap/CMakeFiles/starmap.dir/src/catalog/CatalogManager.cpp.i
.PHONY : src/catalog/CatalogManager.cpp.i

src/catalog/CatalogManager.s: src/catalog/CatalogManager.cpp.s
.PHONY : src/catalog/CatalogManager.s

# target to generate assembly for a file
src/catalog/CatalogManager.cpp.s:
	cd /Users/michelebigi/Documents/Develop/ASTDYN/IOccultCalc && $(MAKE) $(MAKESILENT) -f external/IOC_StarMap/CMakeFiles/starmap.dir/build.make external/IOC_StarMap/CMakeFiles/starmap.dir/src/catalog/CatalogManager.cpp.s
.PHONY : src/catalog/CatalogManager.cpp.s

src/catalog/GaiaClient.o: src/catalog/GaiaClient.cpp.o
.PHONY : src/catalog/GaiaClient.o

# target to build an object file
src/catalog/GaiaClient.cpp.o:
	cd /Users/michelebigi/Documents/Develop/ASTDYN/IOccultCalc && $(MAKE) $(MAKESILENT) -f external/IOC_StarMap/CMakeFiles/starmap.dir/build.make external/IOC_StarMap/CMakeFiles/starmap.dir/src/catalog/GaiaClient.cpp.o
.PHONY : src/catalog/GaiaClient.cpp.o

src/catalog/GaiaClient.i: src/catalog/GaiaClient.cpp.i
.PHONY : src/catalog/GaiaClient.i

# target to preprocess a source file
src/catalog/GaiaClient.cpp.i:
	cd /Users/michelebigi/Documents/Develop/ASTDYN/IOccultCalc && $(MAKE) $(MAKESILENT) -f external/IOC_StarMap/CMakeFiles/starmap.dir/build.make external/IOC_StarMap/CMakeFiles/starmap.dir/src/catalog/GaiaClient.cpp.i
.PHONY : src/catalog/GaiaClient.cpp.i

src/catalog/GaiaClient.s: src/catalog/GaiaClient.cpp.s
.PHONY : src/catalog/GaiaClient.s

# target to generate assembly for a file
src/catalog/GaiaClient.cpp.s:
	cd /Users/michelebigi/Documents/Develop/ASTDYN/IOccultCalc && $(MAKE) $(MAKESILENT) -f external/IOC_StarMap/CMakeFiles/starmap.dir/build.make external/IOC_StarMap/CMakeFiles/starmap.dir/src/catalog/GaiaClient.cpp.s
.PHONY : src/catalog/GaiaClient.cpp.s

src/catalog/GaiaSAODatabase.o: src/catalog/GaiaSAODatabase.cpp.o
.PHONY : src/catalog/GaiaSAODatabase.o

# target to build an object file
src/catalog/GaiaSAODatabase.cpp.o:
	cd /Users/michelebigi/Documents/Develop/ASTDYN/IOccultCalc && $(MAKE) $(MAKESILENT) -f external/IOC_StarMap/CMakeFiles/starmap.dir/build.make external/IOC_StarMap/CMakeFiles/starmap.dir/src/catalog/GaiaSAODatabase.cpp.o
.PHONY : src/catalog/GaiaSAODatabase.cpp.o

src/catalog/GaiaSAODatabase.i: src/catalog/GaiaSAODatabase.cpp.i
.PHONY : src/catalog/GaiaSAODatabase.i

# target to preprocess a source file
src/catalog/GaiaSAODatabase.cpp.i:
	cd /Users/michelebigi/Documents/Develop/ASTDYN/IOccultCalc && $(MAKE) $(MAKESILENT) -f external/IOC_StarMap/CMakeFiles/starmap.dir/build.make external/IOC_StarMap/CMakeFiles/starmap.dir/src/catalog/GaiaSAODatabase.cpp.i
.PHONY : src/catalog/GaiaSAODatabase.cpp.i

src/catalog/GaiaSAODatabase.s: src/catalog/GaiaSAODatabase.cpp.s
.PHONY : src/catalog/GaiaSAODatabase.s

# target to generate assembly for a file
src/catalog/GaiaSAODatabase.cpp.s:
	cd /Users/michelebigi/Documents/Develop/ASTDYN/IOccultCalc && $(MAKE) $(MAKESILENT) -f external/IOC_StarMap/CMakeFiles/starmap.dir/build.make external/IOC_StarMap/CMakeFiles/starmap.dir/src/catalog/GaiaSAODatabase.cpp.s
.PHONY : src/catalog/GaiaSAODatabase.cpp.s

src/catalog/SAOCatalog.o: src/catalog/SAOCatalog.cpp.o
.PHONY : src/catalog/SAOCatalog.o

# target to build an object file
src/catalog/SAOCatalog.cpp.o:
	cd /Users/michelebigi/Documents/Develop/ASTDYN/IOccultCalc && $(MAKE) $(MAKESILENT) -f external/IOC_StarMap/CMakeFiles/starmap.dir/build.make external/IOC_StarMap/CMakeFiles/starmap.dir/src/catalog/SAOCatalog.cpp.o
.PHONY : src/catalog/SAOCatalog.cpp.o

src/catalog/SAOCatalog.i: src/catalog/SAOCatalog.cpp.i
.PHONY : src/catalog/SAOCatalog.i

# target to preprocess a source file
src/catalog/SAOCatalog.cpp.i:
	cd /Users/michelebigi/Documents/Develop/ASTDYN/IOccultCalc && $(MAKE) $(MAKESILENT) -f external/IOC_StarMap/CMakeFiles/starmap.dir/build.make external/IOC_StarMap/CMakeFiles/starmap.dir/src/catalog/SAOCatalog.cpp.i
.PHONY : src/catalog/SAOCatalog.cpp.i

src/catalog/SAOCatalog.s: src/catalog/SAOCatalog.cpp.s
.PHONY : src/catalog/SAOCatalog.s

# target to generate assembly for a file
src/catalog/SAOCatalog.cpp.s:
	cd /Users/michelebigi/Documents/Develop/ASTDYN/IOccultCalc && $(MAKE) $(MAKESILENT) -f external/IOC_StarMap/CMakeFiles/starmap.dir/build.make external/IOC_StarMap/CMakeFiles/starmap.dir/src/catalog/SAOCatalog.cpp.s
.PHONY : src/catalog/SAOCatalog.cpp.s

src/config/ConfigurationLoader.o: src/config/ConfigurationLoader.cpp.o
.PHONY : src/config/ConfigurationLoader.o

# target to build an object file
src/config/ConfigurationLoader.cpp.o:
	cd /Users/michelebigi/Documents/Develop/ASTDYN/IOccultCalc && $(MAKE) $(MAKESILENT) -f external/IOC_StarMap/CMakeFiles/starmap.dir/build.make external/IOC_StarMap/CMakeFiles/starmap.dir/src/config/ConfigurationLoader.cpp.o
.PHONY : src/config/ConfigurationLoader.cpp.o

src/config/ConfigurationLoader.i: src/config/ConfigurationLoader.cpp.i
.PHONY : src/config/ConfigurationLoader.i

# target to preprocess a source file
src/config/ConfigurationLoader.cpp.i:
	cd /Users/michelebigi/Documents/Develop/ASTDYN/IOccultCalc && $(MAKE) $(MAKESILENT) -f external/IOC_StarMap/CMakeFiles/starmap.dir/build.make external/IOC_StarMap/CMakeFiles/starmap.dir/src/config/ConfigurationLoader.cpp.i
.PHONY : src/config/ConfigurationLoader.cpp.i

src/config/ConfigurationLoader.s: src/config/ConfigurationLoader.cpp.s
.PHONY : src/config/ConfigurationLoader.s

# target to generate assembly for a file
src/config/ConfigurationLoader.cpp.s:
	cd /Users/michelebigi/Documents/Develop/ASTDYN/IOccultCalc && $(MAKE) $(MAKESILENT) -f external/IOC_StarMap/CMakeFiles/starmap.dir/build.make external/IOC_StarMap/CMakeFiles/starmap.dir/src/config/ConfigurationLoader.cpp.s
.PHONY : src/config/ConfigurationLoader.cpp.s

src/config/JSONConfigLoader.o: src/config/JSONConfigLoader.cpp.o
.PHONY : src/config/JSONConfigLoader.o

# target to build an object file
src/config/JSONConfigLoader.cpp.o:
	cd /Users/michelebigi/Documents/Develop/ASTDYN/IOccultCalc && $(MAKE) $(MAKESILENT) -f external/IOC_StarMap/CMakeFiles/starmap.dir/build.make external/IOC_StarMap/CMakeFiles/starmap.dir/src/config/JSONConfigLoader.cpp.o
.PHONY : src/config/JSONConfigLoader.cpp.o

src/config/JSONConfigLoader.i: src/config/JSONConfigLoader.cpp.i
.PHONY : src/config/JSONConfigLoader.i

# target to preprocess a source file
src/config/JSONConfigLoader.cpp.i:
	cd /Users/michelebigi/Documents/Develop/ASTDYN/IOccultCalc && $(MAKE) $(MAKESILENT) -f external/IOC_StarMap/CMakeFiles/starmap.dir/build.make external/IOC_StarMap/CMakeFiles/starmap.dir/src/config/JSONConfigLoader.cpp.i
.PHONY : src/config/JSONConfigLoader.cpp.i

src/config/JSONConfigLoader.s: src/config/JSONConfigLoader.cpp.s
.PHONY : src/config/JSONConfigLoader.s

# target to generate assembly for a file
src/config/JSONConfigLoader.cpp.s:
	cd /Users/michelebigi/Documents/Develop/ASTDYN/IOccultCalc && $(MAKE) $(MAKESILENT) -f external/IOC_StarMap/CMakeFiles/starmap.dir/build.make external/IOC_StarMap/CMakeFiles/starmap.dir/src/config/JSONConfigLoader.cpp.s
.PHONY : src/config/JSONConfigLoader.cpp.s

src/config/LibraryConfig.o: src/config/LibraryConfig.cpp.o
.PHONY : src/config/LibraryConfig.o

# target to build an object file
src/config/LibraryConfig.cpp.o:
	cd /Users/michelebigi/Documents/Develop/ASTDYN/IOccultCalc && $(MAKE) $(MAKESILENT) -f external/IOC_StarMap/CMakeFiles/starmap.dir/build.make external/IOC_StarMap/CMakeFiles/starmap.dir/src/config/LibraryConfig.cpp.o
.PHONY : src/config/LibraryConfig.cpp.o

src/config/LibraryConfig.i: src/config/LibraryConfig.cpp.i
.PHONY : src/config/LibraryConfig.i

# target to preprocess a source file
src/config/LibraryConfig.cpp.i:
	cd /Users/michelebigi/Documents/Develop/ASTDYN/IOccultCalc && $(MAKE) $(MAKESILENT) -f external/IOC_StarMap/CMakeFiles/starmap.dir/build.make external/IOC_StarMap/CMakeFiles/starmap.dir/src/config/LibraryConfig.cpp.i
.PHONY : src/config/LibraryConfig.cpp.i

src/config/LibraryConfig.s: src/config/LibraryConfig.cpp.s
.PHONY : src/config/LibraryConfig.s

# target to generate assembly for a file
src/config/LibraryConfig.cpp.s:
	cd /Users/michelebigi/Documents/Develop/ASTDYN/IOccultCalc && $(MAKE) $(MAKESILENT) -f external/IOC_StarMap/CMakeFiles/starmap.dir/build.make external/IOC_StarMap/CMakeFiles/starmap.dir/src/config/LibraryConfig.cpp.s
.PHONY : src/config/LibraryConfig.cpp.s

src/core/CelestialObject.o: src/core/CelestialObject.cpp.o
.PHONY : src/core/CelestialObject.o

# target to build an object file
src/core/CelestialObject.cpp.o:
	cd /Users/michelebigi/Documents/Develop/ASTDYN/IOccultCalc && $(MAKE) $(MAKESILENT) -f external/IOC_StarMap/CMakeFiles/starmap.dir/build.make external/IOC_StarMap/CMakeFiles/starmap.dir/src/core/CelestialObject.cpp.o
.PHONY : src/core/CelestialObject.cpp.o

src/core/CelestialObject.i: src/core/CelestialObject.cpp.i
.PHONY : src/core/CelestialObject.i

# target to preprocess a source file
src/core/CelestialObject.cpp.i:
	cd /Users/michelebigi/Documents/Develop/ASTDYN/IOccultCalc && $(MAKE) $(MAKESILENT) -f external/IOC_StarMap/CMakeFiles/starmap.dir/build.make external/IOC_StarMap/CMakeFiles/starmap.dir/src/core/CelestialObject.cpp.i
.PHONY : src/core/CelestialObject.cpp.i

src/core/CelestialObject.s: src/core/CelestialObject.cpp.s
.PHONY : src/core/CelestialObject.s

# target to generate assembly for a file
src/core/CelestialObject.cpp.s:
	cd /Users/michelebigi/Documents/Develop/ASTDYN/IOccultCalc && $(MAKE) $(MAKESILENT) -f external/IOC_StarMap/CMakeFiles/starmap.dir/build.make external/IOC_StarMap/CMakeFiles/starmap.dir/src/core/CelestialObject.cpp.s
.PHONY : src/core/CelestialObject.cpp.s

src/core/Coordinates.o: src/core/Coordinates.cpp.o
.PHONY : src/core/Coordinates.o

# target to build an object file
src/core/Coordinates.cpp.o:
	cd /Users/michelebigi/Documents/Develop/ASTDYN/IOccultCalc && $(MAKE) $(MAKESILENT) -f external/IOC_StarMap/CMakeFiles/starmap.dir/build.make external/IOC_StarMap/CMakeFiles/starmap.dir/src/core/Coordinates.cpp.o
.PHONY : src/core/Coordinates.cpp.o

src/core/Coordinates.i: src/core/Coordinates.cpp.i
.PHONY : src/core/Coordinates.i

# target to preprocess a source file
src/core/Coordinates.cpp.i:
	cd /Users/michelebigi/Documents/Develop/ASTDYN/IOccultCalc && $(MAKE) $(MAKESILENT) -f external/IOC_StarMap/CMakeFiles/starmap.dir/build.make external/IOC_StarMap/CMakeFiles/starmap.dir/src/core/Coordinates.cpp.i
.PHONY : src/core/Coordinates.cpp.i

src/core/Coordinates.s: src/core/Coordinates.cpp.s
.PHONY : src/core/Coordinates.s

# target to generate assembly for a file
src/core/Coordinates.cpp.s:
	cd /Users/michelebigi/Documents/Develop/ASTDYN/IOccultCalc && $(MAKE) $(MAKESILENT) -f external/IOC_StarMap/CMakeFiles/starmap.dir/build.make external/IOC_StarMap/CMakeFiles/starmap.dir/src/core/Coordinates.cpp.s
.PHONY : src/core/Coordinates.cpp.s

src/map/ChartGenerator.o: src/map/ChartGenerator.cpp.o
.PHONY : src/map/ChartGenerator.o

# target to build an object file
src/map/ChartGenerator.cpp.o:
	cd /Users/michelebigi/Documents/Develop/ASTDYN/IOccultCalc && $(MAKE) $(MAKESILENT) -f external/IOC_StarMap/CMakeFiles/starmap.dir/build.make external/IOC_StarMap/CMakeFiles/starmap.dir/src/map/ChartGenerator.cpp.o
.PHONY : src/map/ChartGenerator.cpp.o

src/map/ChartGenerator.i: src/map/ChartGenerator.cpp.i
.PHONY : src/map/ChartGenerator.i

# target to preprocess a source file
src/map/ChartGenerator.cpp.i:
	cd /Users/michelebigi/Documents/Develop/ASTDYN/IOccultCalc && $(MAKE) $(MAKESILENT) -f external/IOC_StarMap/CMakeFiles/starmap.dir/build.make external/IOC_StarMap/CMakeFiles/starmap.dir/src/map/ChartGenerator.cpp.i
.PHONY : src/map/ChartGenerator.cpp.i

src/map/ChartGenerator.s: src/map/ChartGenerator.cpp.s
.PHONY : src/map/ChartGenerator.s

# target to generate assembly for a file
src/map/ChartGenerator.cpp.s:
	cd /Users/michelebigi/Documents/Develop/ASTDYN/IOccultCalc && $(MAKE) $(MAKESILENT) -f external/IOC_StarMap/CMakeFiles/starmap.dir/build.make external/IOC_StarMap/CMakeFiles/starmap.dir/src/map/ChartGenerator.cpp.s
.PHONY : src/map/ChartGenerator.cpp.s

src/map/ConstellationData.o: src/map/ConstellationData.cpp.o
.PHONY : src/map/ConstellationData.o

# target to build an object file
src/map/ConstellationData.cpp.o:
	cd /Users/michelebigi/Documents/Develop/ASTDYN/IOccultCalc && $(MAKE) $(MAKESILENT) -f external/IOC_StarMap/CMakeFiles/starmap.dir/build.make external/IOC_StarMap/CMakeFiles/starmap.dir/src/map/ConstellationData.cpp.o
.PHONY : src/map/ConstellationData.cpp.o

src/map/ConstellationData.i: src/map/ConstellationData.cpp.i
.PHONY : src/map/ConstellationData.i

# target to preprocess a source file
src/map/ConstellationData.cpp.i:
	cd /Users/michelebigi/Documents/Develop/ASTDYN/IOccultCalc && $(MAKE) $(MAKESILENT) -f external/IOC_StarMap/CMakeFiles/starmap.dir/build.make external/IOC_StarMap/CMakeFiles/starmap.dir/src/map/ConstellationData.cpp.i
.PHONY : src/map/ConstellationData.cpp.i

src/map/ConstellationData.s: src/map/ConstellationData.cpp.s
.PHONY : src/map/ConstellationData.s

# target to generate assembly for a file
src/map/ConstellationData.cpp.s:
	cd /Users/michelebigi/Documents/Develop/ASTDYN/IOccultCalc && $(MAKE) $(MAKESILENT) -f external/IOC_StarMap/CMakeFiles/starmap.dir/build.make external/IOC_StarMap/CMakeFiles/starmap.dir/src/map/ConstellationData.cpp.s
.PHONY : src/map/ConstellationData.cpp.s

src/map/GridRenderer.o: src/map/GridRenderer.cpp.o
.PHONY : src/map/GridRenderer.o

# target to build an object file
src/map/GridRenderer.cpp.o:
	cd /Users/michelebigi/Documents/Develop/ASTDYN/IOccultCalc && $(MAKE) $(MAKESILENT) -f external/IOC_StarMap/CMakeFiles/starmap.dir/build.make external/IOC_StarMap/CMakeFiles/starmap.dir/src/map/GridRenderer.cpp.o
.PHONY : src/map/GridRenderer.cpp.o

src/map/GridRenderer.i: src/map/GridRenderer.cpp.i
.PHONY : src/map/GridRenderer.i

# target to preprocess a source file
src/map/GridRenderer.cpp.i:
	cd /Users/michelebigi/Documents/Develop/ASTDYN/IOccultCalc && $(MAKE) $(MAKESILENT) -f external/IOC_StarMap/CMakeFiles/starmap.dir/build.make external/IOC_StarMap/CMakeFiles/starmap.dir/src/map/GridRenderer.cpp.i
.PHONY : src/map/GridRenderer.cpp.i

src/map/GridRenderer.s: src/map/GridRenderer.cpp.s
.PHONY : src/map/GridRenderer.s

# target to generate assembly for a file
src/map/GridRenderer.cpp.s:
	cd /Users/michelebigi/Documents/Develop/ASTDYN/IOccultCalc && $(MAKE) $(MAKESILENT) -f external/IOC_StarMap/CMakeFiles/starmap.dir/build.make external/IOC_StarMap/CMakeFiles/starmap.dir/src/map/GridRenderer.cpp.s
.PHONY : src/map/GridRenderer.cpp.s

src/map/MapConfiguration.o: src/map/MapConfiguration.cpp.o
.PHONY : src/map/MapConfiguration.o

# target to build an object file
src/map/MapConfiguration.cpp.o:
	cd /Users/michelebigi/Documents/Develop/ASTDYN/IOccultCalc && $(MAKE) $(MAKESILENT) -f external/IOC_StarMap/CMakeFiles/starmap.dir/build.make external/IOC_StarMap/CMakeFiles/starmap.dir/src/map/MapConfiguration.cpp.o
.PHONY : src/map/MapConfiguration.cpp.o

src/map/MapConfiguration.i: src/map/MapConfiguration.cpp.i
.PHONY : src/map/MapConfiguration.i

# target to preprocess a source file
src/map/MapConfiguration.cpp.i:
	cd /Users/michelebigi/Documents/Develop/ASTDYN/IOccultCalc && $(MAKE) $(MAKESILENT) -f external/IOC_StarMap/CMakeFiles/starmap.dir/build.make external/IOC_StarMap/CMakeFiles/starmap.dir/src/map/MapConfiguration.cpp.i
.PHONY : src/map/MapConfiguration.cpp.i

src/map/MapConfiguration.s: src/map/MapConfiguration.cpp.s
.PHONY : src/map/MapConfiguration.s

# target to generate assembly for a file
src/map/MapConfiguration.cpp.s:
	cd /Users/michelebigi/Documents/Develop/ASTDYN/IOccultCalc && $(MAKE) $(MAKESILENT) -f external/IOC_StarMap/CMakeFiles/starmap.dir/build.make external/IOC_StarMap/CMakeFiles/starmap.dir/src/map/MapConfiguration.cpp.s
.PHONY : src/map/MapConfiguration.cpp.s

src/map/MapRenderer.o: src/map/MapRenderer.cpp.o
.PHONY : src/map/MapRenderer.o

# target to build an object file
src/map/MapRenderer.cpp.o:
	cd /Users/michelebigi/Documents/Develop/ASTDYN/IOccultCalc && $(MAKE) $(MAKESILENT) -f external/IOC_StarMap/CMakeFiles/starmap.dir/build.make external/IOC_StarMap/CMakeFiles/starmap.dir/src/map/MapRenderer.cpp.o
.PHONY : src/map/MapRenderer.cpp.o

src/map/MapRenderer.i: src/map/MapRenderer.cpp.i
.PHONY : src/map/MapRenderer.i

# target to preprocess a source file
src/map/MapRenderer.cpp.i:
	cd /Users/michelebigi/Documents/Develop/ASTDYN/IOccultCalc && $(MAKE) $(MAKESILENT) -f external/IOC_StarMap/CMakeFiles/starmap.dir/build.make external/IOC_StarMap/CMakeFiles/starmap.dir/src/map/MapRenderer.cpp.i
.PHONY : src/map/MapRenderer.cpp.i

src/map/MapRenderer.s: src/map/MapRenderer.cpp.s
.PHONY : src/map/MapRenderer.s

# target to generate assembly for a file
src/map/MapRenderer.cpp.s:
	cd /Users/michelebigi/Documents/Develop/ASTDYN/IOccultCalc && $(MAKE) $(MAKESILENT) -f external/IOC_StarMap/CMakeFiles/starmap.dir/build.make external/IOC_StarMap/CMakeFiles/starmap.dir/src/map/MapRenderer.cpp.s
.PHONY : src/map/MapRenderer.cpp.s

src/map/Projection.o: src/map/Projection.cpp.o
.PHONY : src/map/Projection.o

# target to build an object file
src/map/Projection.cpp.o:
	cd /Users/michelebigi/Documents/Develop/ASTDYN/IOccultCalc && $(MAKE) $(MAKESILENT) -f external/IOC_StarMap/CMakeFiles/starmap.dir/build.make external/IOC_StarMap/CMakeFiles/starmap.dir/src/map/Projection.cpp.o
.PHONY : src/map/Projection.cpp.o

src/map/Projection.i: src/map/Projection.cpp.i
.PHONY : src/map/Projection.i

# target to preprocess a source file
src/map/Projection.cpp.i:
	cd /Users/michelebigi/Documents/Develop/ASTDYN/IOccultCalc && $(MAKE) $(MAKESILENT) -f external/IOC_StarMap/CMakeFiles/starmap.dir/build.make external/IOC_StarMap/CMakeFiles/starmap.dir/src/map/Projection.cpp.i
.PHONY : src/map/Projection.cpp.i

src/map/Projection.s: src/map/Projection.cpp.s
.PHONY : src/map/Projection.s

# target to generate assembly for a file
src/map/Projection.cpp.s:
	cd /Users/michelebigi/Documents/Develop/ASTDYN/IOccultCalc && $(MAKE) $(MAKESILENT) -f external/IOC_StarMap/CMakeFiles/starmap.dir/build.make external/IOC_StarMap/CMakeFiles/starmap.dir/src/map/Projection.cpp.s
.PHONY : src/map/Projection.cpp.s

src/occultation/OccultationChartBuilder.o: src/occultation/OccultationChartBuilder.cpp.o
.PHONY : src/occultation/OccultationChartBuilder.o

# target to build an object file
src/occultation/OccultationChartBuilder.cpp.o:
	cd /Users/michelebigi/Documents/Develop/ASTDYN/IOccultCalc && $(MAKE) $(MAKESILENT) -f external/IOC_StarMap/CMakeFiles/starmap.dir/build.make external/IOC_StarMap/CMakeFiles/starmap.dir/src/occultation/OccultationChartBuilder.cpp.o
.PHONY : src/occultation/OccultationChartBuilder.cpp.o

src/occultation/OccultationChartBuilder.i: src/occultation/OccultationChartBuilder.cpp.i
.PHONY : src/occultation/OccultationChartBuilder.i

# target to preprocess a source file
src/occultation/OccultationChartBuilder.cpp.i:
	cd /Users/michelebigi/Documents/Develop/ASTDYN/IOccultCalc && $(MAKE) $(MAKESILENT) -f external/IOC_StarMap/CMakeFiles/starmap.dir/build.make external/IOC_StarMap/CMakeFiles/starmap.dir/src/occultation/OccultationChartBuilder.cpp.i
.PHONY : src/occultation/OccultationChartBuilder.cpp.i

src/occultation/OccultationChartBuilder.s: src/occultation/OccultationChartBuilder.cpp.s
.PHONY : src/occultation/OccultationChartBuilder.s

# target to generate assembly for a file
src/occultation/OccultationChartBuilder.cpp.s:
	cd /Users/michelebigi/Documents/Develop/ASTDYN/IOccultCalc && $(MAKE) $(MAKESILENT) -f external/IOC_StarMap/CMakeFiles/starmap.dir/build.make external/IOC_StarMap/CMakeFiles/starmap.dir/src/occultation/OccultationChartBuilder.cpp.s
.PHONY : src/occultation/OccultationChartBuilder.cpp.s

src/occultation/OccultationData.o: src/occultation/OccultationData.cpp.o
.PHONY : src/occultation/OccultationData.o

# target to build an object file
src/occultation/OccultationData.cpp.o:
	cd /Users/michelebigi/Documents/Develop/ASTDYN/IOccultCalc && $(MAKE) $(MAKESILENT) -f external/IOC_StarMap/CMakeFiles/starmap.dir/build.make external/IOC_StarMap/CMakeFiles/starmap.dir/src/occultation/OccultationData.cpp.o
.PHONY : src/occultation/OccultationData.cpp.o

src/occultation/OccultationData.i: src/occultation/OccultationData.cpp.i
.PHONY : src/occultation/OccultationData.i

# target to preprocess a source file
src/occultation/OccultationData.cpp.i:
	cd /Users/michelebigi/Documents/Develop/ASTDYN/IOccultCalc && $(MAKE) $(MAKESILENT) -f external/IOC_StarMap/CMakeFiles/starmap.dir/build.make external/IOC_StarMap/CMakeFiles/starmap.dir/src/occultation/OccultationData.cpp.i
.PHONY : src/occultation/OccultationData.cpp.i

src/occultation/OccultationData.s: src/occultation/OccultationData.cpp.s
.PHONY : src/occultation/OccultationData.s

# target to generate assembly for a file
src/occultation/OccultationData.cpp.s:
	cd /Users/michelebigi/Documents/Develop/ASTDYN/IOccultCalc && $(MAKE) $(MAKESILENT) -f external/IOC_StarMap/CMakeFiles/starmap.dir/build.make external/IOC_StarMap/CMakeFiles/starmap.dir/src/occultation/OccultationData.cpp.s
.PHONY : src/occultation/OccultationData.cpp.s

src/utils/HttpClient.o: src/utils/HttpClient.cpp.o
.PHONY : src/utils/HttpClient.o

# target to build an object file
src/utils/HttpClient.cpp.o:
	cd /Users/michelebigi/Documents/Develop/ASTDYN/IOccultCalc && $(MAKE) $(MAKESILENT) -f external/IOC_StarMap/CMakeFiles/starmap.dir/build.make external/IOC_StarMap/CMakeFiles/starmap.dir/src/utils/HttpClient.cpp.o
.PHONY : src/utils/HttpClient.cpp.o

src/utils/HttpClient.i: src/utils/HttpClient.cpp.i
.PHONY : src/utils/HttpClient.i

# target to preprocess a source file
src/utils/HttpClient.cpp.i:
	cd /Users/michelebigi/Documents/Develop/ASTDYN/IOccultCalc && $(MAKE) $(MAKESILENT) -f external/IOC_StarMap/CMakeFiles/starmap.dir/build.make external/IOC_StarMap/CMakeFiles/starmap.dir/src/utils/HttpClient.cpp.i
.PHONY : src/utils/HttpClient.cpp.i

src/utils/HttpClient.s: src/utils/HttpClient.cpp.s
.PHONY : src/utils/HttpClient.s

# target to generate assembly for a file
src/utils/HttpClient.cpp.s:
	cd /Users/michelebigi/Documents/Develop/ASTDYN/IOccultCalc && $(MAKE) $(MAKESILENT) -f external/IOC_StarMap/CMakeFiles/starmap.dir/build.make external/IOC_StarMap/CMakeFiles/starmap.dir/src/utils/HttpClient.cpp.s
.PHONY : src/utils/HttpClient.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... starmap"
	@echo "... src/StarMap.o"
	@echo "... src/StarMap.i"
	@echo "... src/StarMap.s"
	@echo "... src/catalog/CatalogManager.o"
	@echo "... src/catalog/CatalogManager.i"
	@echo "... src/catalog/CatalogManager.s"
	@echo "... src/catalog/GaiaClient.o"
	@echo "... src/catalog/GaiaClient.i"
	@echo "... src/catalog/GaiaClient.s"
	@echo "... src/catalog/GaiaSAODatabase.o"
	@echo "... src/catalog/GaiaSAODatabase.i"
	@echo "... src/catalog/GaiaSAODatabase.s"
	@echo "... src/catalog/SAOCatalog.o"
	@echo "... src/catalog/SAOCatalog.i"
	@echo "... src/catalog/SAOCatalog.s"
	@echo "... src/config/ConfigurationLoader.o"
	@echo "... src/config/ConfigurationLoader.i"
	@echo "... src/config/ConfigurationLoader.s"
	@echo "... src/config/JSONConfigLoader.o"
	@echo "... src/config/JSONConfigLoader.i"
	@echo "... src/config/JSONConfigLoader.s"
	@echo "... src/config/LibraryConfig.o"
	@echo "... src/config/LibraryConfig.i"
	@echo "... src/config/LibraryConfig.s"
	@echo "... src/core/CelestialObject.o"
	@echo "... src/core/CelestialObject.i"
	@echo "... src/core/CelestialObject.s"
	@echo "... src/core/Coordinates.o"
	@echo "... src/core/Coordinates.i"
	@echo "... src/core/Coordinates.s"
	@echo "... src/map/ChartGenerator.o"
	@echo "... src/map/ChartGenerator.i"
	@echo "... src/map/ChartGenerator.s"
	@echo "... src/map/ConstellationData.o"
	@echo "... src/map/ConstellationData.i"
	@echo "... src/map/ConstellationData.s"
	@echo "... src/map/GridRenderer.o"
	@echo "... src/map/GridRenderer.i"
	@echo "... src/map/GridRenderer.s"
	@echo "... src/map/MapConfiguration.o"
	@echo "... src/map/MapConfiguration.i"
	@echo "... src/map/MapConfiguration.s"
	@echo "... src/map/MapRenderer.o"
	@echo "... src/map/MapRenderer.i"
	@echo "... src/map/MapRenderer.s"
	@echo "... src/map/Projection.o"
	@echo "... src/map/Projection.i"
	@echo "... src/map/Projection.s"
	@echo "... src/occultation/OccultationChartBuilder.o"
	@echo "... src/occultation/OccultationChartBuilder.i"
	@echo "... src/occultation/OccultationChartBuilder.s"
	@echo "... src/occultation/OccultationData.o"
	@echo "... src/occultation/OccultationData.i"
	@echo "... src/occultation/OccultationData.s"
	@echo "... src/utils/HttpClient.o"
	@echo "... src/utils/HttpClient.i"
	@echo "... src/utils/HttpClient.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	cd /Users/michelebigi/Documents/Develop/ASTDYN/IOccultCalc && $(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

